### ISSUE TITLE
Where to put Fulfillment functions

### ISSUE THREAD

**Issue by pk075** [api-ai/api-ai-facebook#12]
Hi all,

i used this code to get my bot up and running on facebook everything works fine. But now i am at a point where i like to use my own functionality/fulfillment´s eg. calling an food database api. Can anyone take the time and explain to me where in that code i need to write the fulfillment function?

Thanks regards
Philipp

**Comment by xVir** [comment]
Hi, @pk075 
Yes, you could use this code to create a fulfillment or start it as a separate service.

To use this service as a fulfillment provider you have to add some code like

```js
app.post('/fulfill', (req, res) => {
    var obj = {
            speech: 'one two free',
            // displayText: 'one two free',
            // source: 'fulfillment-sample',
            // data: {"param": "value"},
            // messages: [{type: 0, speech: 'one two free'}, {type: 3, imageUrl: 'http://www.example.com/image.png'}]
        };
    return res.json(obj);
});
```

to this place https://github.com/api-ai/api-ai-facebook/blob/master/src/app.js#L240

And then you have to specify this service in api.ai fulfillment settings
https://some_service.herokuapp.com/fulfill

Feel free to ask any questions.
Thanks!

**Comment by pk075** [comment]
Hi, @xVir 

thanks for the quick and detailed answer :) So as i am still trying to get into this whole concept maybe you can help me in understanding.

As an example i got to Intents on api.ai one is the User Types in a specific type of food an the bot should answer with the calories for that kind of food. Let´s call that action here getcalories

Then we have an other intent which gives you a recommendation of recipes based on some foods you typed in. Lets call that action getrecipes.

So i am using fulfillments for both intents. To actually handle the different actions behind those i need to catch wich action is meant out of the JSON file i receive from api.ai right? Or is there an other easy way to handle stuff like that? 

Thanks in advance :)

Greetings 
Philipp

**Comment by xVir** [comment]
Hi, @pk075 
In this case you will receive two types of json in your fulfillment:
```
{
  ...
  "result": {
    "action": "getcalories",
```

```
{
  ...
  "result": {
    "action": "getrecipes",
```

So, you just have to get the `result.action` value and then make switch on it and process the result in different ways.
Now it is just the only way, because of you could specify only one fulfillment URL in an agent, sorry.

Thanks!
