### ISSUE TITLE
Use of sessionId in example code

### ISSUE THREAD

**Issue by Carpetfizz** [api-ai/api-ai-facebook#6]
When you make a request to api.ai you supply it with a sessionId

        let apiaiRequest = apiAiService.textRequest(text,
            {
                sessionId: sessionIds.get(sender)
            });

I understand that the sessionId is a unique identifier used to refer back to a session, to continue the course of conversation. I'm confused as to why this is unused. In the 'response' callback, there are a few function calls like this:

        sendFBMessage(sender, facebookMessage);

which are refering to the `sender` defined at the top of the function. Isn't it possible that two requests could come into `processEvent()` at the same time and that the `response` callback is called for the first request after the second request to `processEvent()` has been set? In this case wouldn't `sender` be referring to the latest request instead of the request that the callback is referring to? Wouldn't we have to keep retrieve the sessionId from the response sent by api.ai and send the message back to the right sender?

Thanks for any clarification

**Comment by xVir** [comment]
Hi, @Carpetfizz 
Yes, it is interesting question.

Local variable in function is related to particular function call. So, every call of `processEvent` will have its own `sender` variable.
Also, in JavaScript there is so-called closure feature. It means, that every inner function will have access to the outer variable([details here](http://stackoverflow.com/questions/111102/how-do-javascript-closures-work)). So, even after `processEvent` will have ended, the `sender` variable will be available with right value for the `response` callback.

Please feel free to ask if my explanation is too confusing for you.
Thanks.

**Comment by Carpetfizz** [comment]
Thanks for the speedy response. That explanation makes a lot of sense, thank you!

**Comment by xVir** [comment]
@Carpetfizz always glad to help ;-)
